<div class="official-rules">
	<p align="center"><strong>Race To DeLeon Sweepstakes</strong><strong> </strong><br />
	  <strong>Official Rules</strong></p>
	<p><strong>NO PURCHASE OR PAYMENT NECESSARY. A PURCHASE WILL NOT IMPROVE YOUR CHANCE OF WINNING.  VOID IN QUEBEC, GUAM, PUERTO RICO, THE U.S. VIRGIN ISLANDS AND OTHER U.S. TERRITORIES AND POSSESSIONS AND WHERE PROHIBITED BY LAW. THIS SWEEPSTAKES IS IN NO WAY SPONSORED, ENDORSED, ADMINISTERED BY, OR ASSOCIATED WITH FACEBOOK,  TWITTER, AND/OR TUMBLR.  </strong></p>
	<p><strong>BY ENTERING THE SWEEPSTAKES ENTRANT AGREES TO THESE OFFICIAL RULES.</strong></p>
	<p><strong><u>Eligibility</u></strong><br />
	  The Race To DeLeon Sweepstakes (the &quot;Sweepstakes&quot;) is open only to legal residents of the fifty (50) United States (including the District of Columbia) and Canada (excluding Quebec), who are thirteen (13) years or older at the time of entry. &nbsp;Void in Quebec, Guam, Puerto Rico, the U.S. Virgin Islands and other U.S. territories and possessions and where prohibited by law. No purchase necessary to enter the Sweepstakes. &nbsp;Employees of ABC, Inc. d/b/a Walt Disney Studios Motion Pictures, 500 South Buena Vista Street, Burbank, CA 90051 (the &quot;Sponsor&quot;), Brandmovers, Inc., 1575 Northside Drive, Building 200, Atlanta, GA 30318 (&quot;Administrator&quot;), Ford Motor Company (&ldquo;Ford&rdquo;), or any of their respective affiliates, subsidiaries, licensors, advertising agencies, or any other company or individual involved with the design, production, execution, marketing or distribution of the motion picture titled &ldquo;Need For Speed&rdquo; and/or the Sweepstakes (collectively with Sponsor and Administrator, the &quot;Sweepstakes Entities&quot;) and their immediate family (spouse, parents and step-parents, grandparents and step-grandparents, siblings and step- siblings, and children and step-children) and household members of each such employee are not eligible to enter or win. &nbsp;The Sweepstakes is subject to all applicable federal, state, municipal, provincial and local laws and regulations. &nbsp;Participation constitutes entrant's full and unconditional agreement to these Official Rules (or the &ldquo;Rules&rdquo;) and Sponsor's decisions, which are final and binding in all matters related to the Sweepstakes. &nbsp;Winning a prize is contingent upon fulfilling all requirements set forth herein.</p>
	<p><strong><u>Sweepstakes Period</u></strong><br />
	  The Sweepstakes begins on January 31, 2014 at 9:00:00 AM Pacific Time (&quot;PST&quot;) and ends on March 16, 2014 at 11:59:59PM PST (the &quot;Sweepstakes Period&quot;). &nbsp;The Website (defined below) clock is the official timekeeper for this Sweepstakes.</p>
	<p><strong><u>How to Enter</u></strong><br />
	  <a name="id.665f82c5954c" id="id.665f82c5954c"></a>During the Sweepstakes Period, there are three possible ways to enter this Sweepstakes as follows:</p>
	<p>(1) If an entrant (&quot;Entrants&quot;) is a first time visitor to www.RaceToDeLeon.com (&ldquo;Website&rdquo;) then the Entrant will fill out the official entry form located on the Website with all required information (collectively, &ldquo;Entry Form&rdquo;).  Entrant must agree to the Race to DeLeon Sweepstakes Official Rules and Terms of Use, then connect to Facebook and accept Facebook permissions to submit the Entry Form  (the &ldquo;Registration&rdquo;).  All Registrations must be submitted by 11:59:59 p.m. PST on March 16, 2014 to be eligible to receive one (1) entry into the Sweepstakes.<strong> </strong>Entrant must accept Facebook permissions to participate and must be a registered member of Facebook with an account in good standing.&nbsp; &nbsp;To become a registered member of Facebook (registration is free), go to <a href="http://www.facebook.com">www.facebook.com</a> and follow the instructions to become a registered member and create an account (&ldquo;<strong>Account</strong>&rdquo;).  <strong>By accepting Facebook permissions, the Race To DeLeon application (1) will have access to your public profile information, including your profile photograph; and (2) WILL ALLOW SPONSOR AND ITS AFFILIATES TO SEND YOU FACEBOOK NOTIFICATIONS PERTAINING TO THE RACE TO DELEON PROMOTION</strong><strong>.</strong><strong> </strong></p>
	<p>(2) If an Entrant has visited the Website before and has previously filled out the Entry Form then the Entrant will need to agree to accept the Race to DeLeon Sweepstakes Official Rules and Terms of Use in order to receive an entry into this Sweepstakes. </p>
	<p>(3)<strong> </strong>Alternatively<strong>, </strong>during the Sweepstakes Period, you may also choose to enter the Sweepstakes by sending an email with the subject line &ldquo;Race to DeLeon Sweepstakes&rdquo; to <a href="mailto:disneysweeps@brandmovers.com">NFSsweeps@brandmovers.com</a>, with your name, email address, state of residence, and date of birth (&ldquo;Email Entry&rdquo;). You will receive one (1) entry for each Email Entry submitted up to the limit provided below. Email Entries will be deemed submitted by the authorized account holder of the email address through which the entry was submitted.</p>
	<p>Upon completion of any one of the above entry methods, including the Email Entry, (each shall be referred to as &ldquo;Basic Entry&rdquo;), Entrant will receive one (1) Entry into the Sweepstakes. <strong></strong></p>
	<p><strong>Basic Entry, including Email Entry, shall be referred to as an &ldquo;Entry&rdquo; or &ldquo;Entries&rdquo;.  Regardless of whether a person has more than one (1) email address or more than one (1) person use the same email address, Entries are limited to one (1) per person/email address (regardless of method of Basic Entry chosen by Entrant) during the Sweepstakes Period.</strong></p>
	<p>Any attempt by any participant to enter by using multiple/different email addresses, identities, registrations and logins, or any other methods will void that participant's entries and that participant may be disqualified, at the sole discretion of Sponsor. &nbsp;Use of any automated system to participate is prohibited and may result in disqualification. Sponsor is not responsible for lost, late, incomplete, invalid, unintelligible or misdirected entries, which may be disqualified. &nbsp;In the event of a dispute regarding who submitted a Registration or Entry, the Registration or Entry will be deemed submitted by the authorized account holder of the e-mail address connected with the Entry Form or the Entry Email, from which the Entry was submitted. &nbsp;&quot;Authorized account holder&quot; is defined as the natural person who is assigned to an e-mail address by Internet access provider, online service provider, or other organization (e.g., business, educational institution, etc.) that is responsible for assigning e-mail addresses for the domain associated with the submitted e-mail address. &nbsp;No automatically generated entries will be accepted.</p>
	<p><strong><u>Privacy Policies and Data Collections</u></strong><br />
	  Information provided by you for this Sweepstakes on the Entry is subject to Sponsor&rsquo;s privacy policy located at <a href="http:/corporate.disney.go.com/corporate/pp.html">http://corporate.disney.go.com/corporate/pp.html</a>.   By entering this Sweepstakes, each Entrant agrees that the Sponsor and/or Administrator has the right to contact the Entrant by (1) email accounts provided on the Entry to administer and fulfill this Sweepstakes; AND (2) Facebook notifications to administer Entrant&rsquo;s participation in the Race To DeLeon Promotions, including any additional sweepstakes, contests, or game play that an Entrant may opt-in to participate through the Race to DeLeon Application during the Sweepstakes Period. <br />
	  <strong>This Sweepstakes is in no way sponsored, endorsed or administered by, or associated with Facebook. &nbsp; Facebook is a registered trademark. &nbsp;Such use is not intended to suggest or imply the sponsorship, endorsement, or the approval of this Sweepstakes by Facebook.</strong></p>
	<p><strong><u>Winner Selection</u></strong><br />
	  There will be a total of one (1) Grand Prize winner (the &ldquo;Grand Prize Winner&rdquo;) in this Sweepstakes, who will be randomly selected by Administrator from among all eligible Entries received throughout the Sweepstakes Period on or about March 17, 2014 (&quot;Drawing Date&quot;). The Potential Winner will be contacted via his/her email as provided on the Entry, and may be awarded a Prize (subject to verification of eligibility and compliance with the terms of these rules). If the Potential Winner is deemed a minor in the state/province of his/her residence, minor must provide Sponsor with contact information for his/her parent/legal guardian, so that Sponsor may contact parent/legal guardian to conduct the verification and fulfillment process as well as to award the prize to such minor&rsquo;s parent/legal guardian.  Sponsor's decisions as to the administration and operation of the Sweepstakes and the selection of potential Winner is final and binding in all matters related to the Sweepstakes. &nbsp;Administrator will send a notification message (&quot;Message&quot;) to the potential Winner's email account on or about the same day of the Drawing Date.</p>
	<p>Failure to respond to the Message within seven (7) days of notification, or return of Message as undeliverable after three (3) attempts will result in disqualification and an alternate potential Winner may be selected, time permitting. <strong>Odds of winning depend on the number of eligible entries received during the Sweepstakes Period.</strong> The prize will be awarded, provided it is validly claimed by April 30, 2014, after which no alternate winner will be selected, nor unclaimed prize awarded. </p>
	<p>THE POTENTIAL WINNER IS SUBJECT TO VERIFICATION BY ADMINISTRATOR AND SPONSOR&rsquo;S DECISIONS ARE FINAL AND BINDING IN ALL MATTERS RELATED TO THE SWEEPSTAKES.</p>
	<p><strong><u>Verification of Potential Winner</u></strong><br />
	  In order to be confirmed as a Winner, and without limitation of any other terms herein, the potential Winner (or Winner&rsquo;s parent/legal guardian if potential Winner is deemed a minor in the state/province of his/her residence) must provide satisfactory proof, as determined by Sponsor in its sole discretion, that such potential Winner is an eligible Entrant, including but not limited to providing a copy of the potential Winner&rsquo;s government-issued identification, and/or additional information required by Sponsor in order to verify eligibility and compliance with these Official Rules. If the potential winner is from Canada, he/she will be required to correctly answer a time-limited skill testing question without any assistance in order to be eligible to receive a prize or such prize will be forfeited.&nbsp; Winner (or Winner&rsquo;s parent/legal guardian if potential Winner is deemed a minor in the state/province of his/her residence) will be required to sign and return to Administrator, within seven (7) days of the date notice is sent, an affidavit of eligibility, and a liability/publicity release (except where prohibited), which release will include the right to use Winner&rsquo;s likeness at the Event (as defined below) in order to claim his/her prize, or such other documents as Sponsor deems necessary, in its sole discretion (collectively, &ldquo;Prize Claim Documents&rdquo;). If a Winner is a minor, a Prize either will be awarded in the name of the parent or legal guardian of such minor Winner.&nbsp; If a potential Winner cannot be contacted, fails to sign and return (or, in the case of a minor, such minor winner&rsquo;s parent or legal guardian fails to sign and return) the Prize Claim Documents within the required time period, potential Winner may be disqualified and may forfeit the prize. In the event that the potential Winner is disqualified for any reason, Sponsor may award the prize to an alternate winner by random drawing from among all remaining eligible entries, time permitting.  </p>
	<p><strong><u>Grand Prize</u></strong><br />
	  One (1) Grand Prize Winner will receive a 2015 Ford Mustang (the &ldquo;Prize&rdquo;). Approximate retail value (&quot;ARV&quot;) of one (1) Grand Prize: $40,000. <br />
	  Ford makes no warranty about the Grand Prize other than that expressed in its New Vehicle Limited Warranty, a printed copy of which shall be furnished with the Grand Prize.  Grand Prize Winner is solely responsible for vehicle registration, license, title, tags and all other expenses associated with the Prize not specifically identified in these Official Rules, including but not limited to taxes, emissions fees, insurance fees, transportation fees, and for all costs and expenses not specifically included above, including, without limitation, all income, federal, state and local sales, luxury, use or other taxes, vehicle maintenance, and insurance costs.  Color, package, factory options, and other Prize specifics to be determined by Ford, in its sole discretion, and are subject to availability.  <strong>Grand Prize Winner acknowledges that the Prize will not exceed the ARV listed above.</strong>  <strong>Grand Prize Winner must take possession of such prize no later than thirty (30) days after receiving notice that the Grand Prize is ready for pick up</strong>.  Grand Prize Winner must possess a valid driver&rsquo;s license and may be required to show proof-of-insurance prior to taking ownership of Grand Prize.  Failure to provide these items may result in Prize forfeiture and selection of an alternate winner. <br />
	  Any difference between the stated retail value and actual value will not be awarded. The Grand Prize Winner will be required to execute and return a Release of Liability prior to participation. Certain restrictions, as determined by Sponsor, may apply. A prize cannot be used in conjunction with any other promotion or offer. Prize elements may not be separated.&nbsp; If Grand Prize Winner cannot comply with these restrictions or any other portion of these Official Rules, the Grand Prize will be forfeited in its entirety and an alternate winner will be chosen. The Grand Prize restrictions/conditions stated herein are not all-inclusive and the Grand Prize described above may be subject to additional restrictions/conditions, which may be stated in the Prize Claim Documents.  <br />
	  Prize is non-transferable and no substitution will be made except as provided herein at the Sponsor's sole discretion. &nbsp;Sponsor reserves the right to substitute the prize for one of equal or greater value for any reason. &nbsp;<br />
	  All taxes (including, without limitation, state and federal income taxes) and the reporting consequences thereof associated with the use and acceptance of a Prize is solely the responsibility of the Grand Prize Winner, who will receive an IRS Form 1099 reflecting the Grand Prize value.<br />
	  The Sweepstakes Entities and any of their officers, directors, shareholders, employees, agents or representatives (the &ldquo;Released Parties&rdquo;) make no warranties, and hereby disclaims any and all warranties, express or implied, concerning any prize furnished in connection with the Sweepstakes.&nbsp;&nbsp;WITHOUT LIMITING THE GENERALITY OF THE FOREGOING AND EXCEPT AS PROVIDED IN THESE RULES, SUCH PRIZE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED BY SPONSOR, AND SPONSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND/OR NON-INFRINGEMENT. <br />
	  <strong><u>Entry Conditions and Release</u></strong><br />
	  By entering, each Entrant (and Entrant&rsquo;s parent/legal guardian, if Entrant is deemed a minor in the state/province of his/her residence) agrees to: (a) comply with and be bound by these Official Rules and the decisions of the Sponsor which are binding and final in all matters relating to this Sweepstakes; (b) release and hold harmless the Released Parties from and against any and all claims, expenses, and liability, including but not limited to negligence and damages of any kind to persons and property, including but not limited to invasion of privacy (under appropriation, intrusion, public disclosure of private facts, false light in the public eye or other legal theory), defamation, slander, libel, violation of right of publicity, infringement of trademark, copyright or other intellectual property rights, property damage, or death or personal injury arising out of or relating to a participant's entry, creation of an entry or submission of an entry, participation in the Sweepstakes, acceptance or use or misuse of prize &nbsp;and/or the broadcast, exploitation or use of entry; and (c) indemnify, defend and hold harmless the Released Parties from and against any and all claims, expenses, and liabilities (including reasonable attorneys fees) arising out of or relating to an Entrant's participation in the Sweepstakes and/or Entrant's acceptance, use or misuse of prize.</p>
	<p><strong><u>General Conditions</u></strong><br />
	  Sponsor reserves the right to cancel, suspend and/or modify the Sweepstakes, or any part of it, for any reason whatsoever, including, without limitation, fire, flood, natural or man-made epidemic of health of other means, earthquake, explosion, labor dispute or strike, act of God or public enemy, satellite or equipment failure, riot or civil disturbance, terrorist threat or activity, war (declared or undeclared) or any federal, state, provincial or local government law, order, or regulation, public health crisis, order of any court or jurisdiction or if any fraud, technical failures or any other factor beyond Sponsor's reasonable control impairs the integrity or proper functioning of the Sweepstakes, as determined by Sponsor in its sole discretion. If the Sweepstakes is terminated before the designated end date, Sponsor will (if possible) select the winner in a random drawing from all eligible, non-suspect entries received as of the date of the event, giving rise to the termination.&nbsp; Inclusion in such drawing shall be each Entrant&rsquo;s sole and exclusive remedy under such circumstances.&nbsp; Sponsor reserves the right in its sole discretion to disqualify any individual it finds to be tampering with the entry process or the operation of the Sweepstakes or to be acting in violation of these Official Rules or any other promotion or in an unsportsmanlike or disruptive manner. Any attempt by any person to deliberately undermine the legitimate operation of the Sweepstakes may be a violation of criminal and civil law, and, should such an attempt be made, Sponsor reserves the right to seek damages from any such person to the fullest extent permitted by law. Only the type and quantity of prizes described in these Rules will be awarded.&nbsp; The invalidity or unenforceability of any provision of these Rules shall not affect the validity or enforceability of any other provision.&nbsp; In the event that any provision is determined to be invalid or otherwise unenforceable or illegal, these Rules shall otherwise remain in effect and shall be construed in accordance with their terms as if the invalid or illegal provision were not contained herein.  Sponsor's failure to enforce any term of these Rules shall not constitute a waiver of that provision.  </p>
	<p><strong><u>Limitations of Liability</u></strong><br />
	  The Released Parties as set forth above are not responsible for: (1) any incorrect or inaccurate information, whether caused by Entrants, printing errors or by any of the equipment or programming associated with or utilized in the Sweepstakes; (2) technical failures of any kind, including, but not limited to malfunctions, interruptions, or disconnections in phone lines or network hardware or software; (3) unauthorized human intervention in any part of the entry process or the Sweepstakes; (4) technical or human error which may occur in the administration of the Sweepstakes or the processing of entries; or (5) any injury or damage to persons or property which may be caused, directly or indirectly, in whole or in part, from Entrant's participation in the Sweepstakes or receipt or use or misuse of any Prize. If for any reason an entry is confirmed to have been erroneously deleted, lost, or otherwise destroyed or corrupted, Entrant's sole remedy is another entry in the Sweepstakes, provided that if it is not possible to award another entry due to discontinuance of the Sweepstakes, or any part of it, for any reason, Sponsor, at its discretion, may elect to hold a random drawing from among all eligible entries received up to the date of discontinuance for any or all of the Prizes offered herein. Entrant further agrees and acknowledges that Sponsor reserves the right to forfeit or award any unclaimed or leftover Prize at its sole discretion. &nbsp;</p>
	<p><strong><u>Disputes/Governing Law </u></strong><br />
	  Entrant (and Entrant&rsquo;s parent/legal guardian, if Entrant is deemed a minor in the state/province of his/her residence) agrees that: <strong>(i)</strong> all disputes, claims and causes of action at law or in equity (individually, &ldquo;Claim&rdquo;) arising out of or relating to this Sweepstakes, the meaning or interpretation of the Rules or the prize awarded shall be resolved by applying the laws of California, without regard to conflict of laws provisions therein, and shall be solely and exclusively brought in the state or federal courts within that state; <strong>(ii)</strong> all Claims shall be resolved individually, without resort to any form of class action; <strong>(iii) </strong>all Claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, but in no event include attorneys&rsquo; fees, and under no circumstances will any entrant be permitted to obtain awards for, and hereby waives all rights to claim, punitive, incidental, special, consequential damages and any other damages, other than for actual out-of-pocket expenses and waives all rights to have damages multiplied or otherwise increased.  Notwithstanding the foregoing, Released Parties shall be entitled to seek injunctive relief (unless otherwise precluded by any other provision of these Official Rules) in the state and federal courts of Los Angeles County. </p>
	<p><strong><u>Sweepstakes Winner</u></strong><br />
	  For the Sweepstakes Winner&rsquo;s name (available after March 31, 2014 and before April 30, 2014), send a hand-printed, self-addressed, stamped envelope to: Winner List, Race To DeLeon Sweepstakes, Brandmovers, Inc., 1575 Northside Drive, Building 200, Atlanta, GA 30318.<strong>  </strong>Residents of Vermont residents omit postage.<strong></strong></p>
	<p><strong><u>Official Rules </u></strong><br />
	  For a copy of these Official Rules (before March 17, 2014) send a hand-printed, self-addressed, stamped envelope to: Official Rules – Race To DeLeon Sweepstakes,<strong> </strong>Brandmovers, Inc., 1575 Northside Drive, Building 200, Atlanta, GA 30318.  Residents of Vermont residents omit postage.  A copy of the Rules may also be obtained by printing this web page.  </p>

</div>